ict_accounts/urls.py
from django.urls import path
from . import views

app_name = 'ict_accounts'

urlpatterns = [
    path('register/', views.register, name = 'register'), 
    path('', views.login_view, name = 'login'),
    path('logout/', views.logout_view, name = 'logout'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('password_change/', views.MyPasswordChangeView.as_view(), name = 'password-change'),
    path('password_change_done/', views.MyPasswordChangeDoneView.as_view(), name = 'password-change-done'),
    path('forgot_password/', views.forgot_password, name='forgot-password'),
    path('reset_password_validate/<uidb64>/<token>/', views.reset_password_validate, name='reset-password-validate'),
    path('reset_password/', views.reset_password, name = 'reset-password'),
]

ict_dash/urls.py
from django.urls import path
from . import views

app_name = 'ict_dash'


urlpatterns =[
    path('dashboard/', views.dash, name='dashboard'),
    path('dash/', views.ContractValueView.as_view(), name='dash'),
]

ict_licenses/urls.py
from django.urls import path

from . import views

app_name = 'ict_licenses'
 
urlpatterns = [  
    path('licenses/', views.LicenseListView.as_view(), name='license-list'),
    path('license_admin/', views.LicenseAdminListView.as_view(), name='license-admin'),
    path('license_detail/<int:pk>/', views.LicenseDetailView.as_view(), name='license-detail'),
    path('license_admin_detail/<int:pk>/',views.LicenseAdminDetailView.as_view(), name='license-admin-detail'),
    path('license_add/', views.LicenseCreateView.as_view(), name='license-add'),
    path('license_update/<int:pk>/', views.LicenseUpdateView.as_view(), name='license-update'),
    path('license_renewal/', views.LicenseRenewalView.as_view(), name='license-renew'),
    path('license_delete/<int:pk>/', views.LicenseDeleteView.as_view(), name='license-delete'),
]

ict_main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    # path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('securelogin/', admin.site.urls),
    path('', include('ict_accounts.urls'), name='accounts'),
    path('', include('ict_contracts.urls'), name ='contracts'), 
    path('', include('ict_licenses.urls'), name ='licenses'), 
    path('', include('ict_profiles.urls'), name='profiles'), 
    path('', include('ict_projects.urls'), name='projects'), 
    path('', include('ict_vendors.urls'), name='vendors'),
    path('', include('ict_dash.urls'), name='dashboard'), 
    path('', include('ict_tasks.urls'), name='tasks'),
    path('__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
# admin.site.site_header ='UL ICT Contracts and Portfolio Admin' 
# admin.site.index_title ='Manage ICT Contracts and Portfolio'

ict_profiles/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from .views import (ProfileListView, ProfileDetailView,
                    ProfileCreateView, ProfileUpdateView,ProfileDeleteView,
                    ProfileAdminListView, ProfileAdminDetailView, MyProfileView, license_notify
                    )

from django.contrib.auth.decorators import login_required

app_name = 'ict_profiles'

urlpatterns = [
    path('profiles/', ProfileListView.as_view(), name = 'profile-list'),
    path('profile_detail/<int:pk>/', ProfileDetailView.as_view(), name ='profile-detail'),
    path('my_profile/<int:pk>/',login_required(MyProfileView.as_view(template_name='ict_profiles/my_profile.html')),name ='my-profile'),
    path('profile_admin/',ProfileAdminListView.as_view(), name = 'profile-admin'),
    path('profile_detail/<int:pk>/', ProfileAdminDetailView.as_view(), name='profile-admin-detail'),
    path('profile_add/', ProfileCreateView.as_view(), name='profile-add'),
    path('profile_update/<int:pk>/', ProfileUpdateView.as_view(), name='profile-update'),
    path('profile_delete/<int:pk>/', ProfileDeleteView.as_view(), name='profile-delete'),
    path('license_notify/', license_notify, name='license-notify')
]

ict_vendors/urls.py
from django.urls import path
from . import views

app_name = 'ict_vendors'


urlpatterns =[
    path('vendors/', views.VendorListView.as_view(), name='vendor-list'),
    path('vendor_admin/', views.VendorAdminListView.as_view(), name='vendor-admin'),
    path('vendor_add/',views.VendorCreateView.as_view(), name='vendor-add'),
    path('vendor_update/<int:pk>/',views.VendorUpdateView.as_view(), name='vendor-update'),
    path('vendor_detail/<int:pk>/',views.VendorDetailView.as_view(), name='vendor-detail'),
    path('vendor_detail_admin/<int:pk>/',views.VendorAdminDetailView.as_view(), name='vendor-detail-admin'),
    path('vendor_delete/<int:pk>/',views.VendorDeleteView.as_view(), name='vendor-delete'),
]

templates/partials/_alerts.html
{% if messages %}
    {% for message in messages %}
        <div id="message" class="container">
            <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
                <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span>
                </button>
                <strong>
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                        Error:

                    {% endif %}
                </strong>
                {{ message }}
            </div>
        </div>
    {% endfor %}
{% endif %}

templates/partials/_footer.html
{% load static %}
<footer class="footer-fixed">
    <div class="pull-center">
        ICT Contracts and Portfolio Management | <strong>Copyright © University of Limpopo
        <script>document.write(new Date().getFullYear());</script>
    </strong> <br>

    </div>
    <div class="clearfix"></div>
</footer>

templates/partials/_sidenav.html
{% load static %}
<div class="col-md-3 left_col menu_fixed">
    <div class="left_col scroll-view" style="background-color:rgb(4, 59, 100)">
        <div class="navbar nav_title text-center" style="border: 0;">

            <a href="" class="site_title" style="background-color:rgb(4, 59, 100)">
                <img src="{% static 'images/ul_logo_2.png' %}" class="text-center" style="width:75px; margin-left:auto; margin-right:auto; display:block;" alt="UL Logo">
            </a>
            <div>
                <!-- <h2 style="color: rgba(167, 143, 10, 0.856); text-decoration: underline; text-align: center; font-size: 20px; font-weight: bold">ICT Licensing & <br> Portfolio Management</h2> -->
            </div>
        </div>

        <div class="clearfix"></div>

        <!-- menu profile quick info -->
        <div class="profile clearfix">

        </div>
        <br>
        <br>
        {% if request.user.is_authenticated or 'password-change' not in request.PATH %}
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu"
                 style="background-color:rgb(4, 59, 100)">
            <div class="menu_section">
                <h3 style="color: rgba(240, 219, 99, 0.856);text-decoration:underline">Regular User Area</h3>
                <ul class="nav side-menu">
                    <li><a href="{% url 'ict_dash:dashboard' %}"><i class="fa fa-tachometer"></i> Dashboard</a></li>
                    <li><a href="{% url 'ict_licenses:license-list' %}"><i class="fa fa-book"> </i> Software Licenses</a></li>
                    <li><a href="{% url 'ict_contracts:contract-list' %}"><i class="fa fa-file"> </i> Contracts</a></li>
                    <li><a href="{% url 'ict_vendors:vendor-list' %}"><i class="fa fa-institution"></i> Vendors</a></li>
                    <!-- <li><a><i class="fa fa-file"></i>Software Licensing<span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">

                            <li><a href="{% url 'ict_vendors:vendor-list' %}"> Vendors</a></li>
                            <li><a href="{% url 'ict_contracts:contract-list' %}"> Contracts</a></li>
                            <li><a href="{% url 'ict_licenses:license-list' %}">Licenses</a></li>
                        </ul>
                    </li> -->

                    <li><a href="{% url 'ict_projects:project-list' %}"><i class="fa fa-list"></i>Projects</a>
                    <li><a href="{% url 'ict_profiles:profile-list' %}"><i class="fa fa-group"></i>User Profiles</a>
                    </li>

                </ul>
            </div>

            <div class="menu_section">
            {% if request.user.is_staff %}

                <h3 style="color: rgba(240, 219, 99, 0.856);text-decoration:underline">Admin User Area</h3>
                <ul class="nav side-menu">
                <li><a><i class="fa fa-laptop"></i>Admin - Frontend <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                        <!-- <li><a href="{% url 'ict_profiles:profile-admin' %}">Manage User Profiles</a></li> -->
                        <li><a href="{% url 'ict_licenses:license-admin' %}">Manage Licenses</a></li>
                        <li><a href="{% url 'ict_contracts:contract-admin' %}">Manage Contracts</a></li>
                        <li><a href="{% url 'ict_vendors:vendor-admin' %}">Manage Vendors</a></li>
                        
                        
                        <!-- <li><a>Manage Portfolio<span class="fa fa-chevron-down"></span></a>
                            <ul class="nav child_menu">
                                <li class="sub_menu"><a href="{% url 'ict_projects:project-admin' %}">Projects</a>
                                </li>
                                </li>
                            </ul>
                        </li> -->
                    </ul>
                </li>
                {% if request.user.is_superuser %}
                    <li><a href="{% url 'admin:index' %}" target="_blank"><i class="fa fa-server"></i>
                        Admin - Back Office
                    </a>
                    </li>
                {% endif %}
            {% endif %}
        </ul>

            <ul class="nav side-menu">
                <li><a href="{% url 'ict_accounts:logout' %}"><i class="fa fa-sign-out"></i> Logout </a></li>
            </ul>
        {% endif %}
        </div>
        </div>

    </div>
</div>

templates/partials/_topnav.html
{% load static %}
<div class="top_nav menu_fixed">
    <div class="nav_menu " style="background-color:rgb(4, 59, 100, 0.9)" >
        <div class="nav toggle">
            <a id="menu_toggle"><i class="fa fa-bars"></i></a>
        </div>
        {% if request.user.is_authenticated %}
            <nav class="nav navbar-nav">
                <ul class=" navbar-right">
                    <li class="nav-item dropdown open" style="padding-left: 15px;">
                        <a href="javascript:;" class="user-profile dropdown-toggle" aria-haspopup="true"
                           id="navbarDropdown" data-toggle="dropdown" aria-expanded="false">
                            <img src="{{ user.profile.photo.url }}" alt="">
                            <span class="text-light">Welcome  ({{ request.user.first_name|upper }})</span>
                        </a>

                        <div class="dropdown-menu dropdown-usermenu pull-right text-secondary"
                             aria-labelledby="navbarDropdown" style="background-color:rgb(4, 59, 100, 0.9)"
                        " >
                        <a class="dropdown-item text-light" href=" {% url 'ict_profiles:my-profile' request.user.pk %}">
                            <i> my</i>Profile
                        </a>

                        <a class="dropdown-item text-light" href="{% url 'ict_accounts:password-change' %}">Change
                            Password</a>
                        <a class="dropdown-item text-light" href="{% url 'ict_accounts:logout' %}"><i
                                class="fa fa-sign-out pull-right"></i> Logout</a>
            </div>
            </li>
            </ul>
            </nav>
        {% endif %}
</div>
</div>