ict_accounts/urls.py
from django.urls import path
from . import views

app_name = 'ict_accounts'

urlpatterns = [
    path('register/', views.register, name = 'register'), 
    path('', views.login_view, name = 'login'),
    path('logout/', views.logout_view, name = 'logout'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('password_change/', views.MyPasswordChangeView.as_view(), name = 'password-change'),
    path('password_change_done/', views.MyPasswordChangeDoneView.as_view(), name = 'password-change-done'),
    path('forgot_password/', views.forgot_password, name='forgot-password'),
    path('reset_password_validate/<uidb64>/<token>/', views.reset_password_validate, name='reset-password-validate'),
    path('reset_password/', views.reset_password, name = 'reset-password'),
]

ict_dash/urls.py
from django.urls import path
from . import views

app_name = 'ict_dash'


urlpatterns =[
    path('dashboard/', views.dash, name='dashboard'),
    path('dash/', views.ContractValueView.as_view(), name='dash'),
]

ict_licenses/urls.py
from django.urls import path

from . import views

app_name = 'ict_licenses'
 
urlpatterns = [  
    path('licenses/', views.LicenseListView.as_view(), name='license-list'),
    path('license_admin/', views.LicenseAdminListView.as_view(), name='license-admin'),
    path('license_detail/<int:pk>/', views.LicenseDetailView.as_view(), name='license-detail'),
    path('license_admin_detail/<int:pk>/',views.LicenseAdminDetailView.as_view(), name='license-admin-detail'),
    path('license_add/', views.LicenseCreateView.as_view(), name='license-add'),
    path('license_update/<int:pk>/', views.LicenseUpdateView.as_view(), name='license-update'),
    path('license_renewal/', views.LicenseRenewalView.as_view(), name='license-renew'),
    path('license_delete/<int:pk>/', views.LicenseDeleteView.as_view(), name='license-delete'),
]

ict_main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    # path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('securelogin/', admin.site.urls),
    path('', include('ict_accounts.urls'), name='accounts'),
    path('', include('ict_contracts.urls'), name ='contracts'), 
    path('', include('ict_licenses.urls'), name ='licenses'), 
    path('', include('ict_profiles.urls'), name='profiles'), 
    path('', include('ict_projects.urls'), name='projects'), 
    path('', include('ict_vendors.urls'), name='vendors'),
    path('', include('ict_dash.urls'), name='dashboard'), 
    path('', include('ict_tasks.urls'), name='tasks'),
    path('__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
# admin.site.site_header ='UL ICT Contracts and Portfolio Admin' 
# admin.site.index_title ='Manage ICT Contracts and Portfolio'

ict_profiles/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from .views import (ProfileListView, ProfileDetailView,
                    ProfileCreateView, ProfileUpdateView,ProfileDeleteView,
                    ProfileAdminListView, ProfileAdminDetailView, MyProfileView, license_notify
                    )

from django.contrib.auth.decorators import login_required

app_name = 'ict_profiles'

urlpatterns = [
    path('profiles/', ProfileListView.as_view(), name = 'profile-list'),
    path('profile_detail/<int:pk>/', ProfileDetailView.as_view(), name ='profile-detail'),
    path('my_profile/<int:pk>/',login_required(MyProfileView.as_view(template_name='ict_profiles/my_profile.html')),name ='my-profile'),
    path('profile_admin/',ProfileAdminListView.as_view(), name = 'profile-admin'),
    path('profile_detail/<int:pk>/', ProfileAdminDetailView.as_view(), name='profile-admin-detail'),
    path('profile_add/', ProfileCreateView.as_view(), name='profile-add'),
    path('profile_update/<int:pk>/', ProfileUpdateView.as_view(), name='profile-update'),
    path('profile_delete/<int:pk>/', ProfileDeleteView.as_view(), name='profile-delete'),
    path('license_notify/', license_notify, name='license-notify')
]

ict_profiles/forms.py
from django import forms

from crispy_forms.helper import FormHelper

from ict_accounts.models import Profile

class DateInput(forms.DateInput):
    input_type = 'date'

class ProfileCreateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields ='__all__'
        widgets = {
            'birth_date': DateInput(attrs={'placeholder':'yyyy-mm-dd'}),
        }
        
    def __init__(self, *args, **kwargs):
        super(ProfileCreateForm, self).__init__(*args, **kwargs)
        self.fields["user"].disabled = True
        self.fields["user"].widget.attrs["readonly"] = True
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-3'
        self.helper.field_class = 'col-lg-9'
    
        self.helper.form_show_labels = True

ict_profiles/views.py
from django.conf import settings
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import (ListView, DetailView, CreateView, 
                                UpdateView, DeleteView)
from ict_accounts.models import Profile
from ict_licenses.models import License
from .forms import ProfileCreateForm
from .filters import ProfileFilter

# Create your views here.
class FilteredListView(ListView):
    
    class FilteredListView(ListView):
        filterset_class = None

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = self.filterset_class(self.request.GET, queryset=queryset)
        return self.filterset.qs.distinct()

    def get_context_data(self, *args, **kwargs):
        context = super(FilteredListView,self).get_context_data(*args,**kwargs)
        # Pass the filterset to the template - it provides the form.
        context['filterset'] = self.filterset
        context['form'] = self.filterset.form
        context['total_users'] = self.filterset.qs.count()
        return context


class ProfileListView(LoginRequiredMixin, FilteredListView):
    model = Profile
    context_object_name = 'profiles'
    filterset_class = ProfileFilter

    paginate_by = 6

    template_name = 'ict_profiles/profile_list.html'    

class ProfileAdminListView(LoginRequiredMixin, ListView):
    model = Profile
    context_object_name = 'profiles_admin'
    template_name = 'ict_profiles/profile_admin.html'
    paginate_by = 6


class ProfileDetailView(LoginRequiredMixin, DetailView):
    model = Profile
    context_object_name = 'profile'
    template_name = 'ict_profiles/profile_detail.html'

    
class ProfileAdminDetailView(LoginRequiredMixin, DetailView):
    model = Profile
    context_object_name = 'profile'
    template_name = 'ict_profiles/profile_admin_detail.html'
    
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['profile_list'] = Profile.objects.all()
        return context

class ProfileCreateView(LoginRequiredMixin, CreateView):
    form_class = ProfileCreateForm
    model = Profile
    
class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = Profile
    form_class = ProfileCreateForm
    template_name = 'ict_profiles/profile_update.html'

    def get_success_url(self):
        return reverse('ict_profiles:profile-admin-detail', kwargs={'pk': self.object.id})
    
    # def form_valid(self, form):
    #     form.instance.user_id = self.request.user.id
    #     return super().form_valid(form)
    
    # def test_func(self):
    #     profile = self.get_object()
    #     if self.request.user.id == profile.user_id:
    #         return True
    #     return False

class MyProfileView(LoginRequiredMixin,UserPassesTestMixin,DetailView):
    #login_url = '/accounts/login_view'
    context_object_name = 'my_profile'
    model = Profile
    template_name = 'ict_profile/my_profile.html'
    

    def get_object(self):
            try:
                self.profile = Profile.objects.get(pk=self.request.user.pk)
            except Profile.DoesNotExist:
                self.profile = None
            return self.profile
        
    def test_func(self):
        profile = self.get_object()
        if self.request.user.pk == profile.pk:
            print('User ID: ',self.request.user.pk, '-- Profile ID: ', profile.pk)
            return True
        return False
    
class ProfileDeleteView(LoginRequiredMixin, DeleteView):
    pass

def license_notify(request):
    profiles = Profile.objects.all()
            
    # for profile in profiles:
    #     if profile.licenses:
    #         for license in profile.licenses.all():
    #             from_email = settings.EMAIL_HOST_USER
    #             to_email = license.owner.user.email
    #             subject = "Notification! Software License Renewal Due"
    #             if license.days_till_renewal <=180:         
    #                 if license.days_till_renewal > 90:
    #                     message = 'Alert! Due date for {} license renewal is in less than 6 months.  Renewal date is on {}'.format(license.name, license.next_renewal_date) 
    #                 elif license.days_till_renewal <= 90 and license.days_till_renewal > 0: 
    #                     message = 'Warning! Due date for {} license renewal is in less than 6 months.  Renewal date is on {}'.format(license.name, license.next_renewal_date) 
    #                 else:
    #                     message = 'Critical! The {} license renewal overdue.  The renewal date was on {}'.format(license.name, license.next_renewal_date) 
    #                 print(message) 
    #             send_mail(
    #                 subject,
    #                 message,
    #                 from_email,
    #                 [to_email],
    #                 fail_silently = True                      
    #              )             
                
            
    context = {
        'profiles':profiles,
       
    }
    
    return render(request, 'ict_profiles/notify.html',context)

templates/ict_profiles/my_profile.html
{% extends "base.html" %}


{% block title %}| {{my_profile.user.username}} details {% endblock title %}

{% block content %}

<!-- page content -->
<div class="right_col" role="main">  
<div class="">
    <div class="page-title">
		<div class="title_left">
            <h3>
               {{my_profile.user.full_name}} <i>  Profile </i>
            
            </h3>
		</div>	
		<div class="title_right">
			<div class="col-md-5 col-sm-5   form-group pull-right top_search">
			
				<nav aria-label="breadcrumb">   
					<ol class="breadcrumb bg-light">
						<li class="breadcrumb-item"><a href="{% url 'ict_dash:dashboard' %}">Home</a></li>
						<li class="breadcrumb-item"> <a href="{% url 'ict_profiles:profile-list' %} ">User Profiles</a> </li>
                        <li class="breadcrumb-item active" aria-current="page">{{my_profile.user.username}} </li>
					</ol>
				</nav>
			</div>
		</div>
	</div>
    
    <div class="clearfix"></div>

    <div class="row">
    <div class="col-md-12 col-sm-12 ">
        <div class="x_panel">
        <div class="x_title">
    
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <div class="col-md-3 col-sm-3  profile_left">
            <div class="profile_img">
                <div id="crop-avatar">
                <!-- Current avatar -->
                <img class="img-circle img-fluid" src="{{my_profile.photo.url}}" height="200" width="200"  alt="Profile Photo" title="Change the avatar">
                </div>
            </div>

            <h3> Designation:   
            
            <span class="text-secondary">
                {{my_profile.position}}
            </span>
         
            </h3>
            <hr>
            <h2> Birth Date: 
            
                <span class="text-secondary">
                    {{my_profile.birth_date|date:"d F"}}
                </span>
             
                </h2>
            <hr>
            <ul class="list-unstyled user_data">
                <li><i class="fa fa-map-marker user-profile-icon"></i> &nbsp;&nbsp;&nbsp;{{my_profile.unit}}
                </li>
                <hr>
                <li><i class="fa fa-phone user-profile-icon"></i> &nbsp;&nbsp;&nbsp; {{my_profile.user.mobile}}
                </li>
                <hr>
                <li>
                <i class="fa fa-briefcase user-profile-icon"></i> &nbsp;&nbsp;&nbsp; <strong>{{my_profile.office_ext}}</strong> 
                </li>
                <hr>
                <li class="m-top-xs">
                <i class="fa fa-envelope user-profile-icon"></i>
                <a href="mailto:{{my_profile.user.email}}" target="_blank"> &nbsp;&nbsp;&nbsp;{{my_profile.user.email}}</a>
                </li>
            </ul>

            <a href="{% url 'ict_profiles:profile-update' my_profile.id %}" class="btn btn-success"><i class="fa fa-edit m-right-xs"></i>Edit Profile</a>
            <br />

            </div>
            <div class="col-md-9 col-sm-9 ">

            <div class="" role="tabpanel" data-example-id="togglable-tabs">
                <span class="ml-2 text-center">
                <h3> Total Licenses:  <span class="text-success">{{my_profile.licenses.all.count}} </span></h3> 
                </span>
                    <div role="tabpanel" class="tab-pane active " id="tab_content1" aria-labelledby="home-tab">

                        <!--Beneficiaries-->
                        <table class="data table table-striped no-margin">
                            <thead>
                                <tr>
                                <th>#</th>
                                <th>License Name</th>
                                <th>Software Category</th>
                                <th >Start Date</th>
                                <th>Next Renewal Date</th>
                                <th>Time to Renewal</th>
                                <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                            
                                {% for license in my_profile.licenses.all %}
                                <tr>
                                <td>{{forloop.counter}}</td>
                                <td>{{license.name}}</td>
                                <td>{{license.software_category}}</td>
                                <td >{{license.inception_date|date:"d F Y"}}</td>
                                <td >{{license.next_renewal_date|date:"d F Y"}}</td>
                                <td>
                                    {{license.next_renewal_date|timeuntil}}
                                </td>
                                <td>
                                    <a href="{% url 'ict_licenses:license-update' license.id %}" >
                                        <span class="glyphicon glyphicon-edit text-info" ></span> Edit 
                                    </a> 
                                </td>
                                </tr>
                                
                                {% empty %}
                                <tr>
                                    <td colspan="6" class="text-center"><strong >No licenses recorded for this user!</strong> </td> 
                                </tr>
                                {% endfor %}  
                                <tr>
                                    <td colspan="6" class="text-center"></td>
                                </tr>  
                                <tr> 
                                    <td colspan="4"></td>
                                    <td colspan="1" class="text-center"> 

                                        <a href="{% url 'ict_profiles:profile-list' %}">
                                            <button class="btn btn-secondary btn-block">User Profiles</button>
                                        </a>                                
                                    </td>
                                    <td colspan="1" class="text-center"> 
                                        {% if not license %}
                                        <a href="{% url 'ict_licenses:license-add' %}">
                                            <button class="btn btn-primary">Add License</button>
                                        </a>
                                        {% else %}
                                        <a href="{% url 'ict_licenses:license-add' %}">
                                            <button class="btn btn-primary">Add More Licenses</button>
                                        </a>
                                        {% endif %}  
                                    </td>
                                </tr>                         
                            </tbody>                 
                        </table>
                    </div>
                </div>
            </div>
            </div>
        </div>
        </div>
    </div>
    </div>
</div>
</div>
<!-- /page content -->

{% endblock content %}

templates/ict_profiles/profile_admin.html
{% extends "base.html" %}

{% block title %} | User Profiles {% endblock title %}

{% block content %}
<div class="right_col" role="main">
<div class="">
<div class="page-title">
	<div class="title_left">
		<h3>User Profiles Administration </small></h3>	
	</div>
	<div class="title_right">
		<div class="col-md-5 col-sm-5   form-group pull-right top_search">
		
			<nav aria-label="breadcrumb">
				<ol class="breadcrumb bg-light">
					<li class="breadcrumb-item"><a href="#">Home</a></li>
					<li class="breadcrumb-item active" aria-current="page">User Profiles</li>
				</ol>
			</nav>
		</div>
	</div>
</div>
	<div class="title_right">
		<div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
		<div class="input-group">
			<span class="input-group-btn">
				<!-- <form action="" method="GET">
					<input type="text" name="mobile_phone" value="{{request.GET.mobile_phone}}" 
					class="form-control" placeholder="Search...">
					<button type="submit" class="btn btn-primary text-white" >Go!</button>
				</form> -->
			</span>
		</div>
		</div>
	</div>
	<div class="clearfix"></div>

	<div class="row">
	<div class="col-md-12">
		<div class="x_panel">
		
		<div class="x_content">
			<div class="row">
				<div class="col-md-3 col-sm-6  ">
					<div class="pricing_footer bg-light">
						<div class="title" >
						<a href="{% url 'ict_accounts:register' %} ">
                            <button class="btn btn-info">Add New User Account</button>
                        </a>
						  
						</div>
					</div>
				</div>
                <div class="col-md-3 col-sm-6  ">
					
				</div>
				<div class="col-md-3 col-sm-6">
					<!-- <div class="pricing_footer bg-light">
						<div class="title">
							<form action="" method="GET">
								<input name="q" type="text" placeholder="Search member">
								<button type="submit" class="btn btn-info"> Go...</button>
							</form>
						</div>
					</div> -->

				</div>

			</div>

			<div class="card-box table-responsive"> 
				<!-- start project list -->
				{% include 'partials/_alerts.html' %}
				<table id="datatable" class="table table-striped table-bordered" style="width:100%">
				<thead>
					<tr>
					<th style="width: 1%">#</th>
					<th style="width: 10%">Member Name</th>
					<th style="width: 10%">Member Image</th>
					<th style="width: 10%">Mobile No.</th>
					<th style="width: 10%">Email Address</th>
					<th style="width: 3%">More Info</th>
					<th style="width: 5%" colspan="3">Actions</th>
					</tr>
				</thead>
				<tbody>
					{% for profile in profiles_admin %}
					 {% if not profile.user.is_superuser  %}
					<tr>
					<td> {{forloop.counter}} </td>
					<th>
					<a href="{% url 'ict_profiles:profile-detail' profile.id %}">	<span class="text-secondary">
                        {{profile.user.full_name}} - {{profile.user.is_superuser}}</span> </a>
					</th>
					<td>
						<ul class="list-inline">
						<li>
							<img src="{{profile.photo.url}}" class="avatar" alt="Avatar">
						</li>
						</ul>
					</td>
					<td>{{profile.user.mobile_number}}</td>
					<td> <a href="mailto:{{profile.user.email}}">{{profile.user.email}}</a> </td>
	
					
					<td style="width: 5%"> 
						<a href="{% url 'ict_profiles:profile-admin-detail' profile.id %} ">
							<span class="glyphicon glyphicon-info-sign text-info"></span> View Details
						</a>
					</td>
					<td style="width: 5%">
						<a href="{% url 'ict_profiles:profile-update' profile.id %}" >
							<span class="glyphicon glyphicon-edit text-success" ></span> Edit Profile
						</a>
					</td>
					<td style="width: 5%">
						<a href="#" disabled >
							<span class="glyphicon glyphicon-trash text-danger" area-hiden="true" > </span> Delete
						</a>
					</td>
			
					</tr>
						{% endif %}
					{% endfor %}
					
				</tbody>
				</table>
				<!-- end project list -->
				<!-- Pagination Section -->
				<div class="row">
					<div class="col-md-12" justify-content-right>
						{% if page_obj.has_other_pages %}
						<ul class="pagination nav navbar-right mx-right" >
							{% if page_obj.has_previous %}
							<li class="page-item">
								<a href="?page={{page_obj.previous_page_number}}" class="page-link">Previous</a>
							</li>
						
							{% else %}
									<li class="page-item disabled">
								<a class="page-link">Previous</a> 
							</li>
							{% endif %}
								{% for i in page_obj.paginator.page_range %}
							{% if page_obj.number == i %}
								<li class="page-item active">
								<a class="page-link">{{i}}</a>
								</li>
							{% else %}
								<li class="page-item">
								<a href="?page={{i}}" class="page-link">{{i}}</a>
								</li>
							{% endif %}
							{% endfor %}
							{% if page_obj.has_next %}
							<li class="page-item">
								<a href="?page={{page_obj.next_page_number}}" class="page-link">Next</a>
							</li>
							{% else %}
							<li class="page-item disabled">
								<a class="page-link">Next</a>
							</li>
							{% endif %}
						</ul>
						{% endif %}
					</div>
				</div>
				<!--End pagination -->
		</div>
		</div>
	</div>
	</div>
</div>
</div>
{% endblock content %} 

templates/ict_profiles/profile_admin_detail.html
{% extends "base.html" %}


{% block title %}| {{profile}} details {% endblock title %}

{% block content %}

<!-- page content -->
<div class="right_col" role="main">  
<div class="">
    <div class="page-title">
		<div class="title_left">
            <h3>
                {% if profile.middlename %}
                {{profile.user.first_name}} {{profile.middlename}} {{profile.user.last_name}} - <i>Profile </i> 
                {% else %}
                {{proile.user.first_name}} {{profile.user.last_name}} - <i>  Profile </i>
                {% endif %}
            </h3>
		</div>	
		<div class="title_right">
			<div class="col-md-5 col-sm-5   form-group pull-right top_search">
			
				<nav aria-label="breadcrumb">   
					<ol class="breadcrumb bg-light">
						<li class="breadcrumb-item"><a href="{% url 'ict_dash:dashboard' %}">Home</a></li>
						<li class="breadcrumb-item"> <a href="{% url 'ict_profiles:profile-admin' %} ">User Profiles</a> </li>
                        <li class="breadcrumb-item active" aria-current="page">{{profile.user.username}} </li>
					</ol>
				</nav>
			</div>
		</div>
	</div>
    
    <div class="clearfix"></div>

    <div class="row">
    <div class="col-md-12 col-sm-12 ">
        <div class="x_panel">
        <div class="x_title">
    
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <div class="col-md-3 col-sm-3  profile_left">
            <div class="profile_img">
                <div id="crop-avatar">
                <!-- Current avatar -->
                <img class="img-circle img-fluid" src="{{profile.photo.url}}" height="200" width="200"  alt="Profile Photo" title="Change the avatar">
                </div>
            </div>

            <h3> Designation:   
            
            <span class="text-secondary">
                {{profile.position}}
            </span>
         
            </h3>
            <hr>
            <h2> Birth Date: 
            
                <span class="text-secondary">
                    {{profile.birth_date|date:"d F"}}
                </span>
             
                </h2>
            <hr>
            <ul class="list-unstyled user_data">
                <li><i class="fa fa-map-marker user-profile-icon"></i> &nbsp;&nbsp;&nbsp;{{profile.unit}}
                </li>
                <hr>
                <li><i class="fa fa-phone user-profile-icon"></i> &nbsp;&nbsp;&nbsp; {{profile.mobile}}
                </li>
                <hr>
                <li>
                <i class="fa fa-briefcase user-profile-icon"></i> &nbsp;&nbsp;&nbsp; <strong>{{profile.office_ext}}</strong> 
                </li>
                <hr>
                <li class="m-top-xs">
                <i class="fa fa-envelope user-profile-icon"></i>
                <a href="mailto:{{profile.user.email}}" target="_blank"> &nbsp;&nbsp;&nbsp;{{profile.user.email}}</a>
                </li>
            </ul>

            <a href="{% url 'ict_profiles:profile-update' profile.pk %}" class="btn btn-success"><i class="fa fa-edit m-right-xs"></i>Edit Profile</a>
            <br />

            </div>
            <div class="col-md-9 col-sm-9 ">

            <div class="" role="tabpanel" data-example-id="togglable-tabs">
                <span class="ml-2 text-center">
                <h3> Total Licenses:  <span class="text-success">{{profile.licenses.all.count}} </span></h3> 
                </span>
                    <div role="tabpanel" class="tab-pane active " id="tab_content1" aria-labelledby="home-tab">

                        <!--Beneficiaries-->
                        <table class="data table table-striped no-margin">
                            <thead>
                                <tr>
                                <th>#</th>
                                <th>License Name</th>
                                <th>Software Category</th>
                                <th >Start Date</th>
                                <th>Next Renewal Date</th>
                                <th>Time to Renewal</th>
                                <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                            
                                {% for license in profile.licenses.all %}
                                <tr>
                                <td>{{forloop.counter}}</td>
                                <td>{{license.name}}</td>
                                <td>{{license.software_category}}</td>
                                <td >{{license.inception_date|date:"d F Y"}}</td>
                                <td >{{license.next_renewal_date|date:"d F Y"}}</td>
                                <td>
                                    {{license.next_renewal_date|timeuntil}}
                                </td>
                                <td>
                                    <a href="#" >
                                        <span class="glyphicon glyphicon-edit text-info" ></span> Edit 
                                    </a> 
                                </td>
                                </tr>
                                
                                {% empty %}
                                <tr>
                                    <td colspan="6" class="text-center"><strong >No licenses recorded for this user!</strong> </td> 
                                </tr>
                                {% endfor %}  
                                <tr>
                                    <td colspan="6" class="text-center"></td>
                                </tr>  
                                <tr> 
                                    <td colspan="4"></td>
                                    <td colspan="1" class="text-center"> 

                                        <a href="{% url 'ict_profiles:profile-admin' %}">
                                            <button class="btn btn-secondary btn-block">User Profiles</button>
                                        </a>                                
                                    </td>
                                
                                </tr>                         
                            </tbody>                 
                        </table>
                    </div>
                </div>
            </div>
            </div>
        </div>
        </div>
    </div>
    </div>
</div>
</div>
<!-- /page content -->

{% endblock content %}