ict_contracts/urls.py
from django.urls import path
from . import views

app_name = 'ict_contracts'

urlpatterns = [  
    path('contracts/', views.ContractListView.as_view(), name='contract-list'),
    path('contract_admin/', views.ContractAdminListView.as_view(), name='contract-admin'),
    path('contract_detail/<int:pk>/', views.ContractDetailView.as_view(), name='contract-detail'),
    path('contract_admin_detail/<int:pk>/',views.ContractAdminDetailView.as_view(), name='contract-admin-detail'),
    path('contract_add/', views.ContractCreateView.as_view(), name='contract-add'),
    path('contract_update/<int:pk>/', views.ContractUpdateView.as_view(), name='contract-update'),
    path('contract_delete/<int:pk>/', views.ContractDeleteView.as_view(), name='contract-delete'),
]

ict_dash/urls.py
from django.urls import path
from . import views

app_name = 'ict_dash'


urlpatterns =[
    path('dashboard/', views.dash, name='dashboard'),
    path('dash/', views.ContractValueView.as_view(), name='dash'),
]

ict_licenses/urls.py
from django.urls import path

from . import views

app_name = 'ict_licenses'
 
urlpatterns = [  
    path('licenses/', views.LicenseListView.as_view(), name='license-list'),
    path('license_admin/', views.LicenseAdminListView.as_view(), name='license-admin'),
    path('license_detail/<int:pk>/', views.LicenseDetailView.as_view(), name='license-detail'),
    path('license_admin_detail/<int:pk>/',views.LicenseAdminDetailView.as_view(), name='license-admin-detail'),
    path('license_add/', views.LicenseCreateView.as_view(), name='license-add'),
    path('license_update/<int:pk>/', views.LicenseUpdateView.as_view(), name='license-update'),
    path('license_renewal/', views.LicenseRenewalView.as_view(), name='license-renew'),
    path('license_delete/<int:pk>/', views.LicenseDeleteView.as_view(), name='license-delete'),
]

ict_main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    # path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('securelogin/', admin.site.urls),
    path('', include('ict_accounts.urls'), name='accounts'),
    path('', include('ict_contracts.urls'), name ='contracts'), 
    path('', include('ict_licenses.urls'), name ='licenses'), 
    path('', include('ict_profiles.urls'), name='profiles'), 
    path('', include('ict_projects.urls'), name='projects'), 
    path('', include('ict_vendors.urls'), name='vendors'),
    path('', include('ict_dash.urls'), name='dashboard'), 
    path('', include('ict_tasks.urls'), name='tasks'),
    path('__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
# admin.site.site_header ='UL ICT Contracts and Portfolio Admin' 
# admin.site.index_title ='Manage ICT Contracts and Portfolio'

ict_licenses/models.py
from django.db import models

# Create your models here.
from django.db import models
from decimal import Decimal
from django.urls import reverse
from ict_contracts.models import Contract
from ict_accounts.models import Account, Profile
from ict_vendors.models import Vendor

from datetime import datetime, date, timedelta
from django.utils import timezone
from decimal import Decimal

LICENSE_SERVICE_CHOICES = [
    ('Support and Maintenance','Support and Maintenance'),
    ('Annual Subscription', 'Annual Subscription'),
    ('EULA','End user License Agreement'),   
    ('Click Through','Click Through'),
]

RENEWAL_TERM_CHOICES = [ 
    ('Annual Renewal','Annual Renewal'),
    ('Once-Off','Once-Off'), 
    ('Term Contract','Term Contract'),
]

SOFTWARE_CATEGORY_CHOICES = [
    ('Productivity','Productivity'),
    ('Collaboration','Collaboration'),
    ('ERP','ERP'),
    ('CRM','CRM'),
    ('Learning Management System','Learning Management System'),
    ('Operating System','Operating System'),
    ('Database Management System','Database Management System'),
    ('Business Intelligence','Business Intelligence'),
    ('Data & Statistical Analytics','Data & Statistical Analytics'),
    ('Network Management','Network Management'),
    ('IT Service Management','IT Service Management'),
    ('Communication','Communication'),
    ('Collaboration','Collaboration'),
    ('Business Application','Business Application'),
    ('Academic Specialist Software','Academic Specialist Software'), 
]

USER_BASE_CHOICES = [
    ('Students','Students'),
    ('Academics','Academics'),
    ('Academics & Students','Academics & Students'),
    ('Admin Staff','Admin Staff'),
    ('Admin Staff & Students','Admin Staff & Students'),
    ('All Staff', 'All Staff'),
    ('All Staff & Students','All Staff & Students'),
    ('Academics Specialist','Academics Specialist'),
    ('ICT Staff','ICT Staff'),
]

PRICING_MODEL_CHOICES = [
    ('Retainer','Retainer'),
    ('Seats','Seats'),
    ('Cores','Cores'),
    ('Minutes','Minutes'),
    ('Storage', 'Storage'),
    ('Minutes & Storage','Minutes & Storage'),
]

class License(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()  
    contract = models.ForeignKey(Contract,on_delete=models.DO_NOTHING, null=True, blank=True, 
                                    related_name='licenses')
    software_category = models.CharField(verbose_name="Software Category", max_length=250, 
                                            choices=SOFTWARE_CATEGORY_CHOICES)
    renewal_term = models.CharField(verbose_name="Renewal Term", max_length=250, 
                                        choices=RENEWAL_TERM_CHOICES)
    pricing_model = models.CharField(verbose_name="Pricing Model" ,max_length=200, 
                                        choices=PRICING_MODEL_CHOICES)
    start_date = models.DateTimeField(verbose_name="Inception Date", null=True, blank=True)
    next_renewal_date = models.DateField(verbose_name="Next Renewal Date" ,blank=True, 
                                            null=True, editable=False)
    current_cost = models.DecimalField(default=Decimal('0.0'), decimal_places=2,
                                        max_digits=10, verbose_name="Current Cost")
    is_renewed = models.BooleanField(verbose_name="Renew License", default=False)
    service_provider = models.ForeignKey(Vendor, verbose_name="Service Provider", 
                                            on_delete=models.CASCADE, related_name='licenses')
    user_base = models.CharField(verbose_name="User Base" ,max_length=250, 
                                    choices=USER_BASE_CHOICES)
    num_admin_users = models.PositiveIntegerField(verbose_name="Number of Admin Users", 
                                                    null=True, blank=True)
    num_end_users = models.PositiveIntegerField(verbose_name="Number of End Users", 
                                                null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True) 
    owner = models.ForeignKey(Profile, on_delete=models.DO_NOTHING, related_name='licenses')
    is_closed = models.BooleanField(default=False)

    def __str__(self):
        return self.name
 
    class Meta:
        ordering = ('-id',)
        
    def get_absolute_url(self):
        return reverse ('ict_licenses:license-detail', kwargs={'pk':self.pk})
    
    def save(self, *args, **kwargs):
        renewal_delta = timedelta(days=365)
        if self.start_date:
            self.next_renewal_date = self.start_date + renewal_delta
        super(License,self).save(*args, **kwargs)
        
    def update(self, *args, **kwargs):
        renewal_delta = timedelta(days=365)
        if self.renewal:
            self.next_renewal_date = self.start_date + renewal_delta
        super(License, self).update(*args, **kwargs)
                   
    @property
    def days_till_renewal(self):
        today = date.today()
        days_till = self.next_renewal_date - today
        days_until = str(days_till).split(' ',1)[0]
        int_days_until = int(days_until)
        return int_days_until  
    
class LicenseRenewal(models.Model):
    license = models.ForeignKey(License, on_delete=models.DO_NOTHING, related_name='renewals')
    renewal_date = models.DateField()
    renewal_amount = models.DecimalField(default=Decimal(0.0), max_digits=10, decimal_places=2)
    pr_number = models.CharField(max_length=30, null=True, blank=True)
    po_number = models.CharField(max_length=30, null=True, blank=True)
    is_paid = models.BooleanField(default=False)
    # renewal_count = models.IntegerField(default=0, verbose_name='Renewal Count')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f'{self.license} renewal on - {self.renewal_date} for {self.renewal_amount}'
    
    def save(self, *args, **kwargs):
        if self.po_number is not None:
            self.is_paid = True
        return super(LicenseRenewal, self).save(*args, **kwargs)
            
    
    @property
    def renewal_status(self):
        if self.pr_number == None and self.po_number == None:
            status = "Not started"
        elif self.pr_number  and self.po_number == None:
            status = "PR stage"
        elif self.po_number:
            status = "Renewal completed"
        return status
          
    
            
    
    

ict_licenses/forms.py
from django.forms import ModelForm
from django import forms
from django.forms import inlineformset_factory
from crispy_forms.helper import FormHelper
from crispy_forms.bootstrap import FormActions
from crispy_forms.layout import Layout, Submit, Row, Column, Button

from .models import License, LicenseRenewal
 
class DateInput(forms.DateInput):
    input_type = 'date'
    
class LicenseCreateForm(ModelForm):
    
    class Meta:
        model = License
        exclude = ['owner','is_renewed']
        widgets = {
            'start_date':DateInput(attrs={'placeholder':'yyyy-mm-dd'}), 
            'name':forms.TextInput(attrs= {'placeholder':'License Unique Name'}),  
            'description':forms.Textarea(attrs= {'placeholder':'License Description'}),    
        } 
    

    def __init__(self, *args, **kwargs):
        super(LicenseCreateForm, self).__init__(*args, **kwargs)
        self.fields['description'].widget.attrs = {'rows':3}
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-3'
        self.helper.field_class = 'col-lg-9'
    
        self.helper.form_show_labels = True
        
class LicenseRenewalForm(ModelForm):
    class Meta:
        model = LicenseRenewal
        fields = ('license','renewal_date','renewal_amount',
                'pr_number','po_number')
        
        widgets = widgets = {
            'renewal_date':DateInput(attrs={'placeholder':'yyyy-mm-dd'}),
        } 
        
    def __init__(self, *args, **kwargs):
        super(LicenseRenewalForm, self).__init__(*args, **kwargs)
        self.fields['license'].widget.attrs['read-only'] = True
        self.fields['license'].disabled = True
        self.fields['license'].required = False
        self.fields['renewal_date'].label = "Renewal Date"
        # self.fields['start_date'].required = True
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-3'
        self.helper.field_class = 'col-lg-9'
           
        
    
    

ict_licenses/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib import messages
from django.db.models import Sum 
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import (ListView,DetailView,
                                CreateView,UpdateView,DeleteView)

from .models import License, LicenseRenewal
from .forms import LicenseCreateForm, LicenseRenewalForm

from datetime import datetime, date, timedelta
from django.utils import timezone
from .filters import LicenseFilter

# Create your views here.

class FilteredListView(ListView):
    filterset_class = None

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = self.filterset_class(self.request.GET, queryset=queryset)
        return self.filterset.qs.distinct()

    def get_context_data(self, *args, **kwargs):
        context = super(FilteredListView,self).get_context_data(*args,**kwargs)
        # Pass the filterset to the template - it provides the form.
        context['filterset'] = self.filterset
        context['form'] = self.filterset.form
        context['total_licenses'] = self.filterset.qs.count()
        return context
    
class LicenseListView(LoginRequiredMixin ,FilteredListView):
    model = License
    template_name = 'ict_licenses/license_list.html'
    filterset_class = LicenseFilter
    context_object_name = 'licenses'
    paginate_by = 5
    
    def get_context_data(self, *args, **kwargs):
        context= super(LicenseListView, self).get_context_data(*args, **kwargs)
        return context

class LicenseAdminListView(LoginRequiredMixin, FilteredListView):
    model = License
    context_object_name = 'licenses'
    filterset_class = LicenseFilter
    template_name = 'ict_licenses/license_admin.html'
    paginate_by = 5
    
    def get_context_data(self, *args, **kwargs):
        context = super(LicenseAdminListView, self).get_context_data(*args, **kwargs)
        return context 

class LicenseDetailView(LoginRequiredMixin, DetailView):
    model = License
    context_object_name ='license'
    template_name ='ict_licenses/license_detail.html'
    
class LicenseAdminDetailView(LoginRequiredMixin, DetailView):
    model = License
    context_object_name = 'license'
    template_name ='ict_licenses/license_admin_detail.html'
    
    def get_context_data(self,*args, **kwargs):     
        context = super(LicenseAdminDetailView, self).get_context_data(*args,**kwargs)
        context['amount_outstanding'] = self.object.name
        return context
    
    
class LicenseCreateView(LoginRequiredMixin, CreateView):
    form_class = LicenseCreateForm
    model = License
    # template_name ='licenses/license-form-test.html'
    
    def form_valid(self, form):
        form.instance.owner_id = self.request.user.id
        return super().form_valid(form)
    
class LicenseUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    form_class = LicenseCreateForm
    model = License
    context_object_name = 'license'
    template_name ='ict_licenses/license_update.html'
       
    def form_valid(self, form):
        form.instance.owner_id = self.request.user.id
        return super().form_valid(form)
    
    def test_func(self):
        license = self.get_object()  
        
        if self.request.user.id == license.owner_id:
            print('User ID: ',self.request.user.id, '-- Owner ID: ', license.owner_id)
            return True
        return False  

class LicenseRenewalView(LoginRequiredMixin,CreateView):
    form_class = LicenseRenewalForm
    model = LicenseRenewal
    context_object_name = 'license_renewal'
    template_name ='ict_licenses/license_renew.html'
    
    def form_valid(self, form):  
        form.instance.owner_id = self.request.user.id
        form.save()
        messages.add_message(
            self.request, messages.SUCCESS, f'{form.instance.name}license has been succesfully renewed! Renewal date starts on {form.instance.renewal_date}!')
        return super().form_valid(form)
        
    # def test_func(self, *args, **kwargs):
    #     self.license = self.get_object()
    #     if self.request.user.id == self.license.owner_id:
    #         # print('User ID: ',self.request.user.id, '-- Owner ID: ', license.owner_id)
    #         return True
        
    #     return False
        #     errors = messages.error(self.request,  f'You are not allowed to edit this {license.name} license')
        # return r
    
    
class LicenseDeleteView(LoginRequiredMixin, UserPassesTestMixin,DeleteView):
    model = License
    success_url = reverse_lazy('ict_licenses:license-admin')
    
    def test_func(self, *args, **kwargs):
        self.license = self.get_object()
        if self.request.user.id == self.license.owner_id:
            # print('User ID: ',self.request.user.id, '-- Owner ID: ', license.owner_id)
            return True
        
        return False

templates/ict_licenses/license_admin_detail.html
{% extends "base.html" %}
{% load humanize %}

{% block title %}| {{license}} details {% endblock title %}

{% block content %}

<!-- page content -->
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
        <div class="title_left">
            <h3>{{license.name}} License Details </h3>
        </div>

        <div class="title_right">
            <div class="col-md-5 col-sm-5   form-group pull-right top_search">
            
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb bg-light">
                        <li class="breadcrumb-item"><a href="{% url 'ict_licenses:license-list' %}">All Licenses</a></li>
                        <li class="breadcrumb-item active" aria-current="page">{{license.name}} </li>
                    </ol>
                </nav>
            </div>
        </div>
        </div>
        
        <div class="clearfix"></div>

        <div class="row">
        <div class="col-md-12">
            <div class="x_panel">
            

            <div class="x_content">

            <div class="col-md-9 col-sm-9  ">
                {% include 'partials/_alerts.html' %}
                <ul class="stats-overview">
                    <li>
                    <span class="name"> Current License Cost </span>
                    <span class="value text-secondary"> R{{license.current_cost|intcomma}} </span>
                    </li>
                    <li>
                    <span class="name"> License Start Date:</span>
                    <span class="value text-success">{{license.start_date|date:'d F Y'}}</span>
                    </li>
                    <li class="hidden-phone">              
                    <span class="name"> Expiry Date  </span>     
                    <span class="value text-danger"> {{license.next_renewal_date|date:'d F Y'}} </span>
                    </li>
                </ul>
                <hr>
                <br>
                <ul class="stats-overview">
                    <li>
                {% if license.days_till_renewal > 180 %}
                    <!-- <span class="name"> Current License Cost </span> -->
                    <span class="value"> <strong class="btn btn-sm btn-block btn-success">License Status: Ok!  </strong> </span>
                    <span class="value text-secondary"> 
                                Time to renewal is: {{license.next_renewal_date|timeuntil}}                    
                    </span>
                    {% elif  license.days_till_renewal < 180  and license.days_till_renewal > 90 %} 
                    <span class="value "><strong class="btn btn-sm btn-block btn-primary">Status: Attention!  </strong> </span>
                    <span class="value text-secondary"> 
                                Time to renewal is:{{license.next_renewal_date|timeuntil}}                    
                    </span>
                    {% elif license.days_till_renewal < 90 and license.days_till_renewal >= 0 %} 
                    <span class="value"><strong class=" btn btn-sm btn-block btn-warning">License Renewal Status: Warning! </strong> </span>
                    <span class="value text-secondary">
                        Time to  renewal is: {{license.next_renewal_date|timeuntil}}
                    </span>
                    {% else %}
                    <span class="value"><strong class="btn btn-sm btn-block btn--danger">License Renewal Status: Overdue! </strong></span>
                    <span class="value text-secondary">
                            Renewal is overdue by:  {{license.next_renewal_date|timesince}}     
                    </span>
                {% endif %}
                </li>
                
                <li>               
                    <span class="name"><strong class="btn btn-sm btn-block btn-light"> Responsible Manager
                        </strong>               
                    </span>  
                    <span class="value text-secondary">{{license.owner}}</span>                          
                </li>
                <li>
                    {% if license.contract %}
                    <span class="name"><strong class="btn btn-sm btn-block btn-light">Contract Type
                        </strong>               
                    </span>  
                    <span class="value text-secondary">
                       <a href="{% url 'ict_contracts:contract-detail' license.contract.id %}">{{license.contract.agreement_type}}</a> 
                    </span>             
                    {% else %}
                    <span class="name"><strong class="btn btn-sm btn-block btn-light">Contract Type:</strong>
                    </span>   
                    <span class="value text-secondary">No Contract</span>      
                    {% endif %}
                </li>
                </ul>
                <br />
                <div>
                    <hr>
                    <h4>More Information </h4>

                    <!-- end of user messages -->
                    <ul class="messages">
                    <div class="col-md-6 col-sm-6">
                        <li>
                        
                            <div class="message_wrapper">
                            <h4 class="heading">License Description</h4>
                            <blockquote class="message">{{license.description}} </blockquote>
                            
                            
                            </div>
                        </li>
                        <li>
                            
                            <div class="message_wrapper">
                            <h4 class="heading">Software Category</h4>
                            <blockquote class="message">{{license.software_category}} </blockquote>
                            <br />
                        
                            </div>
                        </li>
                        <li>
                            
                            <div class="message_wrapper">
                            <h4 class="heading">Renewal Terms</h4>
                            <blockquote class="message">{{license.renewal_term}} </blockquote>
                            <br />
                    
                            </div>
                        </li>
                     </div>
                    <div class="col-md-6 col-sm-6">

                        <li>
                            <div class="message_wrapper">
                            <h4 class="heading">User Base</h4>
                            <blockquote class="message">{{license.user_base}} </blockquote>
                            <br />           
                            </div>
                        </li>
                        <li>
                            <div class="message_wrapper">
                            <h4 class="heading">Number of Admin Users</h4>
                            <blockquote class="message">{{license.num_admin_users|intcomma}} </blockquote>
                            <br />
                    
                            </div>
                        </li>
                        <li>
                            <div class="message_wrapper">
                            <h4 class="heading">Number of End Users</h4>
                            <blockquote class="message">{{license.num_end_users|intcomma}} </blockquote>
                            <br />
                    
                            </div>
                        </li>

                    </div>
                    
                    </ul>
                    <!-- end of user messages -->
                </div>
            </div>
                <!-- start project-detail sidebar -->
            <div class="col-md-3 col-sm-3  ">

                <section class="panel">

                    <div class="x_title">
                    <h2>Contact Information</h2>
                    <div class="clearfix"></div>
                    </div>
                    <div class="panel-body">
                    
                    <br />

                    <div class="project_detail">

                        <p class="title"><h5>Service Provider</h5> </p>
                      
                        <p>{{license.service_provider.name}}</p>
                        <br>
                        <p class="title"><h5>Service Provider Contact Person</h5> </p>
                       
                        <p><i class="fa fa-user text-secondary"></i>&nbsp;&nbsp;&nbsp;{{license.service_provider.contact_person}}</p>
                        <p><i class="fa fa-phone text-primary"> </i>&nbsp;&nbsp;&nbsp; {{license.service_provider.contact_phone}}</p>
                        <p> <i class="fa fa-envelope text-info"></i>
                            &nbsp;&nbsp;&nbsp; 
                           <a href="mailto:{{license.service_provider.email}}"> {{license.service_provider.email}}</p></a>
                    </div>

                    <br />
                    <h5>UL Contacts</h5>
                    <ul class="list-unstyled project_files">
                        <li><a href=""><i class="fa fa-user"></i> {{license.owner.user.full_name}}</a>
                        </li>
                        <li><a href=""><i class="fa fa-mobile text-primary"></i> {{license.owner.user.mobile_number}}</a>
                        </li>
                        <li><a href=""><i class="fa fa-phone text-secondary"></i> ext. {{license.owner.office_ext}}</a>
                        </li>
                        <li><a href="{{license.owner.user.email}}"><i class="fa fa-envelope text-info"></i> {{license.owner.user.email}}</a>
                        </li>
                       
                        <li>
                            {% if license.contract.contract_document %}
                            <a href="{{license.contract.contract_document.url}}" target="_blank"> <i class="fa fa-file-pdf-o text-danger"></i> 
                                {{license.contract.description}}</a>
                            {% else %}
                            No Term Contract.  The license is renewed annually 
                            {% endif %}
                        </li>         
                    </ul>
                    <br />

                    <div class="text-center mtop20">
                        <a href="{% url 'ict_licenses:license-admin' %}" class="btn btn-sm btn-secondary">License List</a>
                        <a href="{% url 'ict_licenses:license-update' license.id %}" class="btn btn-sm btn-info">Edit License</a>
                        <a href="{% url 'ict_licenses:license-renew' %}" class="btn btn-sm btn-success">Renew License</a>
                    </div>
                    </div>

                </section>

                </div>
                <!-- end project-detail sidebar -->

            </div>
            </div>
        </div>
        </div>
    </div>
    </div>
    <!-- /page content -->

{% endblock content %}

templates/ict_licenses/license_confirm_delete.html
{% extends "base.html" %}
{% load humanize %}


{% block title %} | Delete License {% endblock title %}


{% block content %}
<!-- page content -->
    <div class="right_col" role="main">
        <div class="">
        <div class="page-title">
            <div class="title_left">
            
            </div>
        
        </div>
        
        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-12">
            <div class="x_panel">
            <div class="x_title">
                
                
            <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <!-- start project list -->
            <div class="col-md-12 col-sm-12  ">
            <div class="x_panel">
            <div class="x_title">
                
                
            <div class="clearfix"></div>
            </div>
            <div class="x_content">

                <div class="bs-example" data-example-id="simple-jumbotron">
                    <div class="jumbotron ">
                        
                        <h3 class="text-warning text-center" > <strong class="bg-secondary">Warning! </strong> </h3>
                        <h2 class="text-center"> 
                            <br>
                            <br>
                            Are you sure you want to delete  
                            <strong >{{object.name}}</strong> 
                            from the list of ICT licenses?
                        </h2>
                            <br>
                        <p class="text-center">This will <span class="text-danger">permanently remove</span>  the license from the database!
                        </p>
                    </div>
                    <br>
                    
                    <form action="" method="POST">
                        {% csrf_token %}
                        <p class="text-center"> 
                            <input type="submit" class="btn btn-danger" value="Confirm"/>
                            <a class="btn btn-secondary" href="{% url 'ict_licenses:license-admin' %}">Cancel</a>
                        </p>     
                    </form>
                    
                </div>

            </div>
            </div>
        </div>
                <!-- end project list -->

                </div>
            </div>
            </div>
        </div>
        </div>
    </div>
    <!-- /page content -->

{% endblock content %}