ict_contracts/urls.py
from django.urls import path
from . import views

app_name = 'ict_contracts'

urlpatterns = [  
    path('contracts/', views.ContractListView.as_view(), name='contract-list'),
    path('contract_admin/', views.ContractAdminListView.as_view(), name='contract-admin'),
    path('contract_detail/<int:pk>/', views.ContractDetailView.as_view(), name='contract-detail'),
    path('contract_admin_detail/<int:pk>/',views.ContractAdminDetailView.as_view(), name='contract-admin-detail'),
    path('contract_add/', views.ContractCreateView.as_view(), name='contract-add'),
    path('contract_update/<int:pk>/', views.ContractUpdateView.as_view(), name='contract-update'),
    path('contract_delete/<int:pk>/', views.ContractDeleteView.as_view(), name='contract-delete'),
]

ict_dash/urls.py
from django.urls import path
from . import views

app_name = 'ict_dash'


urlpatterns =[
    path('dashboard/', views.dash, name='dashboard'),
    path('dash/', views.ContractValueView.as_view(), name='dash'),
]

ict_licenses/urls.py
from django.urls import path

from . import views

app_name = 'ict_licenses'
 
urlpatterns = [  
    path('licenses/', views.LicenseListView.as_view(), name='license-list'),
    path('license_admin/', views.LicenseAdminListView.as_view(), name='license-admin'),
    path('license_detail/<int:pk>/', views.LicenseDetailView.as_view(), name='license-detail'),
    path('license_admin_detail/<int:pk>/',views.LicenseAdminDetailView.as_view(), name='license-admin-detail'),
    path('license_add/', views.LicenseCreateView.as_view(), name='license-add'),
    path('license_update/<int:pk>/', views.LicenseUpdateView.as_view(), name='license-update'),
    path('license_renewal/', views.LicenseRenewalView.as_view(), name='license-renew'),
    path('license_delete/<int:pk>/', views.LicenseDeleteView.as_view(), name='license-delete'),
]

ict_main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    # path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('securelogin/', admin.site.urls),
    path('', include('ict_accounts.urls'), name='accounts'),
    path('', include('ict_contracts.urls'), name ='contracts'), 
    path('', include('ict_licenses.urls'), name ='licenses'), 
    path('', include('ict_profiles.urls'), name='profiles'), 
    path('', include('ict_projects.urls'), name='projects'), 
    path('', include('ict_vendors.urls'), name='vendors'),
    path('', include('ict_dash.urls'), name='dashboard'), 
    path('', include('ict_tasks.urls'), name='tasks'),
    path('__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
# admin.site.site_header ='UL ICT Contracts and Portfolio Admin' 
# admin.site.index_title ='Manage ICT Contracts and Portfolio'

ict_projects/urls.py
from django.urls import path
from . import views

app_name = 'ict_projects'


urlpatterns =[
    path('projects/', views.ProjectListView.as_view(), name='project-list'),
    path('project_admin/',views.ProjectAdminListView.as_view(), name='project-admin'),
    # path('project_admin/', views.project_list, name='project-admin'),
    path('project_detail/<int:pk>/',views.ProjectDetailView.as_view(), name='project-detail'),
    path('project_add/', views.ProjectCreateView.as_view(), name='project-add'),
    path('project_update/<int:pk>/', views.ProjectUpdateView.as_view(), name='project-update'),
    path('project_admin_detail/<int:pk>/', views.ProjectAdminDetailView.as_view(), name='project-admin-detail'),
    path('project_delete/<int:pk>/', views.ProjectDeleteView.as_view(), name='project-delete'),
]
    

ict_vendors/urls.py
from django.urls import path
from . import views

app_name = 'ict_vendors'


urlpatterns =[
    path('vendors/', views.VendorListView.as_view(), name='vendor-list'),
    path('vendor_admin/', views.VendorAdminListView.as_view(), name='vendor-admin'),
    path('vendor_add/',views.VendorCreateView.as_view(), name='vendor-add'),
    path('vendor_update/<int:pk>/',views.VendorUpdateView.as_view(), name='vendor-update'),
    path('vendor_detail/<int:pk>/',views.VendorDetailView.as_view(), name='vendor-detail'),
    path('vendor_detail_admin/<int:pk>/',views.VendorAdminDetailView.as_view(), name='vendor-detail-admin'),
    path('vendor_delete/<int:pk>/',views.VendorDeleteView.as_view(), name='vendor-delete'),
]

ict_dash/views.py
# imports from django modules and libraries
from django.shortcuts import render
from django.views.generic import TemplateView
from math import pi
import pandas as pd
from django.db.models import Count, Q, F

# imports from custom modules
from ict_contracts.models import Contract   
from ict_licenses.models import License
from ict_projects.models import Project
from ict_vendors.models import Vendor 
from ict_accounts.models import Account

#imports form bokeh
from bokeh.plotting import figure, show
from bokeh.embed import components
from bokeh.models import ColumnDataSource, CustomJSTickFormatter
from bokeh.models.tools import HoverTool
from bokeh.transform import factor_cmap, cumsum
from bokeh.palettes import (Greens5, GnBu5, Reds5, Blues5, Category20c,
                        Category20_10, Category20c, Category10_3, 
                        Vibrant3, Spectral10, Cividis, Category20b_3
                        )


# Views functionality for the dashboard graphs.
def dash(request):
    num_contracts = Contract.objects.all().count()
    num_licenses = License.objects.all().count()
    num_projects = Project.objects.all().count()
    num_vendors = Vendor.objects.all().count()
    num_users = Account.objects.all().count()
      
    locations = Contract.objects.order_by('supplier__location_footprint').values_list(
                            'supplier__location_footprint').annotate(
                                locations = Count('supplier__location_footprint')
                            )
    x = dict(locations)
    
    data = pd.Series(x).reset_index(name='value').rename(columns={'index': 'locality'})
 
    
    data['angle'] = data['value']/data['value'].sum() * 2*pi
    data['color'] = None if len(data) == 0 else Category10_3
    
    p3 = figure(height=400, title="ICT Contracts by Supplier Nationality Footprint", toolbar_location=None,
           tools="hover", tooltips="@locality: @value", x_range=(-0.5, 1.0))
    
    p3.wedge(x=0, y=1, radius=0.4, 
        start_angle=cumsum('angle', include_zero=True), end_angle=cumsum('angle'),
        line_color="white", fill_color='color', legend_field='locality', source=data)
    
    p3.axis.axis_label = None
    p3.axis.visible = False
    p3.grid.grid_line_color = None
    p3.title.text_font_size = "18px"
    p3.title.align = 'center'
 
    nationailty_list = [ n[0] for n in locations]
    nationality_counts = [c[1] for c in locations ]
    
# Plotting Contracts values for horizontal bar graph graph
    contracts = Contract.objects.order_by('total_value')
    count = len(contracts)
    contract_names = [c.name for c in contracts][-5:count]
    total_values = [int(v.total_value) for v in contracts][-5:count]
    contract_type = [v.agreement_type for v in contracts][-5:count]
    supplier = [v.supplier.name for v in contracts][-5:count]
    duration = [v.duration for v in contracts][-5:count]
    location = [v.supplier.location_footprint for v in contracts][-5:count]
    
    
    source = ColumnDataSource(data = dict(contract_names=contract_names, 
                                          total_values=total_values,
                                          supplier=supplier,
                                          contract_type=contract_type,
                                          duration=duration,
                                          location=location,
                                          )
                              )
   
    p = figure(y_range = contract_names,  height=200, 
               title="Top 5 Contracts by Total Term Value",  toolbar_location=None, tools="")
    p.hbar(y='contract_names', right='total_values', height=0.5, 
           source=source, 
        #    legend_field = 'total_values',
           fill_color=factor_cmap(
               'contract_names',
    palette=None if len(data) == 0 else Blues5,
               factors=contract_names,
           ),
           fill_alpha=0.9,
        )
    
    p.title.align = 'center'
    p.title.text_font_size = "18px"
    p.ygrid.grid_line_color = None
    p.xaxis.minor_tick_line_color = None
    p.xaxis.formatter = CustomJSTickFormatter(code='''
                                            if (tick < 1e3){
                                                var unit = ''
                                                var num =  (tick).toFixed(2)
                                              }
                                              else if (tick < 1e6){
                                                var unit = 'k'
                                                var num =  (tick/1e3).toFixed(2)
                                              }
                                              else{
                                                var unit = 'm'
                                                var num =  (tick/1e6).toFixed(2)
                                                }
                                            return `R ${num}${unit}`
                                           '''
                                           )
    hover1 = HoverTool()
    hover1.tooltips = """
    <div style = "background-color:rgb(4, 26, 61); color:#fff" width=250, height=250 >
        <!--<img src="@logo" alt="" height=40 width=60 >--!>
       <h3><strong >Vendor: </strong>@supplier</h3>
       <h3 style="color:orange"> <strong  >Total Value: </strong> R@total_values</h3>  
    </div> 
    """
    p.add_tools(hover1)
    
    script, div = components(p)
    
#Plotting Licenses values graph
    count = License.objects.count()
    
    licenses = License.objects.order_by('current_cost')
    
    license_names = [c.name for c in licenses][-5:count]
    current_values = [int(v.current_cost) for v in licenses][-5:count]
    categories = [cat.software_category for cat in licenses][-5:count]
    vendor = [v.service_provider.name for v in licenses][-5:count]
    location = [v.service_provider.location_footprint for v in licenses][-5:count]
    
    source = ColumnDataSource(data = dict(license_names=license_names, 
                                          current_values=current_values,
                                          categories = categories,
                                          vendor=vendor,
                                          location=location,
                                          )
                              )
   
    p2 = figure(y_range = license_names,  height=200, 
                title="Top 5 licenses by Current Value",  toolbar_location=None, tools="")
    p2.hbar(y='license_names', right='current_values', height=0.5, 
            source=source, 
            # legend_field='current_values',
            fill_color=factor_cmap(
               'license_names',
    palette= None if len(license_names) == 0 else Greens5[:],
               factors=license_names,
               
           ), 
            fill_alpha=0.9
        )
    
    p2.title.align = 'center'
    p2.title.text_font_size = "18px"
    p2.ygrid.grid_line_color = None
    p2.xaxis.minor_tick_line_color = None
    p2.xaxis.formatter = CustomJSTickFormatter(code='''
                                            if (tick < 1e3){
                                                var unit = ''
                                                var num =  (tick).toFixed(2)
                                              }
                                              else if (tick < 1e6){
                                                var unit = 'k'
                                                var num =  (tick/1e3).toFixed(2)
                                              }
                                              else{
                                                var unit = 'm'
                                                var num =  (tick/1e6).toFixed(2)
                                                }
                                            return `R ${num}${unit}`
                                           '''
                                           )
    # Tooltips
    hover = HoverTool()
    hover.tooltips = """
        <div style = "background-color:rgb(4, 26, 61); color:#fff" width=250, height=250 >
            <!--<img src="@logo" alt="" height=40 width=60 >--!>
        <h3><strong >Service Provider: </strong>@vendor</h3>
        <h3 style="color:orange"> <strong  >Current Cost: </strong> R@current_values</h3>  
        </div>   
    """
    p2.add_tools(hover)
    
# Plotting Project graphs
    try:
        pass
    except:
        pass
    
    projects = Project.objects.order_by('-total_cost')
    project_names = [c.name for c in projects][-5:count]

    project_total_value = [int(v.total_cost) for v in projects][-5:count]
    project_vendor = [v.service_provider.name for v in projects][-5:count]

    source = ColumnDataSource(data = dict(project_names=project_names, 
                                          project_total_value=project_total_value, 
                                          project_vendor = project_vendor,
                                          )
                            ) 
    p4 = figure(x_range= project_names,
                height=400, 
                title="Top 5 Projects by Total Cost",  
                toolbar_location=None, tools="")
    p4.vbar(x ="project_names", top="project_total_value",  
            width=0.2, 
            source=source, 
            legend_field='project_total_value',
            bottom=0,

            fill_color=factor_cmap(
               'project_names',
               palette=  Reds5, #None if len(data) == 0 else Cividis[len(data)],
               factors=project_names,           
           ), 
             fill_alpha=0.9
        )
    
    p4.yaxis.minor_tick_line_color = None
    p4.title.text_font_size = "18px"
    p4.yaxis.formatter = CustomJSTickFormatter(code='''
                                            if (tick < 1e3){
                                                var unit = ''

templates/ict_dash/dash.html
{% extends "base.html" %}
{%load static %}

{% block title %}
    Dashboard
{% endblock title %}



{% block content %}

  <!-- page content -->
   <!-- page content -->
   <div class="right_col" role="main">
    <div class="">

      <div class="row">
        <div class="col-md-6 col-sm-6  ">
          <canvas id="myChart" width="600" height="400"></canvas> 
        </div>

        <div class="col-md-6 col-sm-6  ">
          <div class="x_panel">
            
            
          </div>
        </div>  

      </div>

      <div class="row">
        <div class="col-md-6 col-sm-12">
          {%  for contract_name in contract_name_list %}
            <ul>
              <li> <strong>{{contract_name}} </strong></li>
            </ul>
            {% endfor %}

        </div>
        <div class="col-md-6 col-sm-12">
          {%  for contract_value in contract_value_list %}
            <ul>
              <li> <strong>{{contract_value}} </strong></li>
            </ul>
            {% endfor %}

        </div>

      </div>
      
       

        
          
          </div>
        </div>
      </div>
      <div class="clearfix"></div>
      <br />
    </div>
  </div>
  <!-- /page content -->
<!-- Chartjs Scripts-->

<script>
  // jquery function
  $(document).ready(function(){
          var ctx = document.getElementById('myChart').getContext('2d');
          var myChart = new Chart(ctx, {
              type: 'bar',
              data: {
                  labels: [{% for data in qs%}'{{data.name}}',{%endfor%}], //loop through queryset, 
                  datasets: [{
                      label: '# of users',
                      data: [{%for data in qs%}{{data.total_value}},{%endfor%}],
                      backgroundColor: [
                          'rgba(255, 99, 132, 0.2)', 
                          'rgba(54, 162, 235, 0.2)',
                          'rgba(255, 206, 86, 0.2)',
                          'rgba(75, 192, 192, 0.2)',
                          'rgba(153, 102, 255, 0.2)'
                          
                      ],
                      borderColor: [
                          'rgba(255, 99, 132, 1)',
                          'rgba(54, 162, 235, 1)',
                          'rgba(255, 206, 86, 1)',
                          'rgba(75, 192, 192, 1)',
                          'rgba(153, 102, 255, 1)'
                    
                      ],
                      borderWidth: 1
                  }]
              },
              options: {
                  scales: {
                      y: {
                          beginAtZero: true
                      }
                  }
              }
  });
      });
  </script>
  
{% endblock content %}

templates/ict_dash/dash2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!--Chart js-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" integrity="sha256-Uv9BNBucvCPipKQ2NS9wYpJmi8DTOEfTA/nH2aoJALw=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css" integrity="sha256-aa0xaJgmK/X74WM224KMQeNQC2xYKwlAt08oZqjeF0E=" crossorigin="anonymous" />
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

    <title>Dash2</title>
    <script>
        // jquery function
        $(document).ready(function(){
                var ctx = document.getElementById('myChart').getContext('2d');
                var myChart = new Chart(ctx, {
                    type: 'doughnut',
                    data: {
                        labels: [{% for data in qs %}'{{data.name}}',{% endfor %}] //loop through queryset, 
                        datasets: [{
                            label: '# of users',
                            data: [{% for data in qs %}{{data.total_value}},{% endfor %}],
                            backgroundColor: [
                                'rgba(255, 99, 132, 0.2)', 
                                'rgba(54, 162, 235, 0.2)',
                                'rgba(255, 206, 86, 0.2)',
                                'rgba(75, 192, 192, 0.2)',
                                'rgba(153, 102, 255, 0.2)'        
                            ],
                            borderColor: [
                                'rgba(255, 99, 132, 1)',
                                'rgba(54, 162, 235, 1)',
                                'rgba(255, 206, 86, 1)',
                                'rgba(75, 192, 192, 1)',
                                'rgba(153, 102, 255, 1)'
                           
                            ],
                            borderWidth: 1
                        }]
                    },
                    options: {
                        scales: {
                            y: {
                                beginAtZero: true
                            }
                        }
                    }
        });
            });
        </script>

</head>
<body>
    <canvas id="myChart" width="600" height="400"></canvas>  
</body>
</html>

templates/ict_dash/dashboard.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Dashboard
{% endblock title %}  


<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.1.2/chart.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.1.2/Chart.min.css" integrity="sha256-aa0xaJgmK/X74WM224KMQeNQC2xYKwlAt08oZqjeF0E=" crossorigin="anonymous" />


{% block content %}
<!-- page content -->
<div class="right_col" role="main">
    <div class="">
    <div class="page-title">
        <div class="title_left">
        <h3> ICT Portfolio Dashboard  </h3>
        </div>    
    </div>
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12">
        <div class="x_panel">          
            <div class="x_content">
                {% include 'partials/_alerts.html' %}
            <div class="row">

                <div class="col-md-3" >                  
                    <a href="{% url 'ict_contracts:contract-list' %} ">
                        <div class="caption text-center" style="background-color:rgb(102, 205, 170, 0.6)">
                            <div class="glyphicon glyphicon-folder-open text-danger" > 
                                <span class="text-muted" style="color:rgb(59, 47, 47);font-size:xx-large;font-weight:bolder">   {{num_contracts}}<span style="font-size:x-large"> Contracts</span> </span> 
                            </div>
                        
                        </div>
                    </a>
                </div>
                <div class="col-md-3">              
                <a href="{% url 'ict_licenses:license-list' %}">
                    <div class="caption text-center" style="background-color:rgb(135, 206, 235, 0.6)">
                        <div class="glyphicon glyphicon-file text-success" > 
                            <span  class="text-muted" style="color:rgb(59, 47, 47);font-size:xx-large;font-weight:bolder">   {{num_licenses}}<span style="font-size:x-large;font-weight:bolder"> Software Licenses</span> </span> 
                        </div>
                    </div>
                </a>             
                </div>
                <div class="col-md-3">       
                <a href="{% url 'ict_projects:project-list' %}">
                    <div class="caption text-center" style="background-color:rgb(255, 215, 0, 0.6)">
                        <div class="glyphicon glyphicon-tasks text-primary" > 
                            <span class="text-muted" style="color:rgb(214, 76, 76);font-size:xx-large;font-weight:bolder">   {{num_projects}}<span x style="font-size:x-large; font-weight:bolder"> Projects</span> </span> 
                        </div>               
                    </div>
                </a>
               </div>
                <div class="col-md-3">
            <a href="{% url 'ict_vendors:vendor-list' %}">
                    <div class="caption text-center" style="background-color:rgba(250, 128, 114, 0.6)">
                        <div class="glyphicon glyphicon-home text-secondary" > 
                            <span class="text-muted" style="color:rgb(59, 47, 47);font-size:xx-large;font-weight:bolder">   {{num_vendors}}<span style="font-size:x-large"> Vendors</span> </span> 
                        </div>                 
                    </div>            
                </a>   
                      
                </div>     
            </div>
            </div>
            <!--Start top leyer graphs-->
            <div class="x_panel">

                <div class="x_content">
            

            </div>      
            <div class="row">
            <div class="jumbotron p-3 col-md-12 sm-12">
               <div class="col-md-6 sm-12">
                {% if num_contracts == 0 %}
                    <h2> Data not available! Graph will show once data has been captured. </h2>       
                {% else %}
                    {{div|safe}}
                {% endif %}
               </div>
               <div class="col-md-6 sm-12"> 
                {% if num_licenses == 0 %}
                    <h2> Data not available! Graph will show once data has been captured. </h2>       
                {% else %}            
                    {{div2|safe}}
                {% endif %}
               </div> 
            </div>
            </div>
         
            <div class="row ">
                <div class="jumbotron p-3 col-md-12 sm-12">
                    <div class="col-md-6 sm-12">
                        {% if num_contracts == 0 %}
                            <h2> Data not available! Graph will show once data has been captured. </h2>       
                        {% else %}
                        {{div3|safe}}
                        {% endif %}
                    </div>

                    <div class="col-md-6 sm-12">
                        {% if num_projects == 0 %}
                            <h2> Data not available! Graph will show once data has been captured. </h2>       
                        {% else %}
                            {{div4|safe}}
                        {% endif %}
                    </div> 
                </div>
             </div>  
             
             

            </div>
        </div>      
        </div>
        </div>
    </div>
    </div>
</div>
<!-- /page content -->



{% endblock content %}